// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/ai/bulk-extract-preferences': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/ai/bulk-extract-preferences.post').default>>>>
    }
    '/api/admin/analytics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/analytics.get').default>>>>
    }
    '/api/admin/bulk-sms': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/bulk-sms.post').default>>>>
    }
    '/api/admin/notify-incomplete-profiles': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/notify-incomplete-profiles.post').default>>>>
    }
    '/api/admin/notify-match': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/notify-match.post').default>>>>
    }
    '/api/admin/notify-missing-details': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/notify-missing-details.post').default>>>>
    }
    '/api/admin/notify-user-missing-details': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/notify-user-missing-details.post').default>>>>
    }
    '/api/admin/quality-audit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/quality-audit.post').default>>>>
    }
    '/api/admin/request-match-feedback': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/request-match-feedback.post').default>>>>
    }
    '/api/admin/seed-users': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/seed-users.post').default>>>>
    }
    '/api/admin/shots/resend-sms': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/shots/resend-sms.post').default>>>>
    }
    '/api/admin/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id].delete').default>>>>
    }
    '/api/admin/users/verify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/verify.post').default>>>>
    }
    '/api/admin/vouches/resend-sms': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/vouches/resend-sms.post').default>>>>
    }
    '/api/ai/extract-preferences': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/extract-preferences.post').default>>>>
    }
    '/api/ai/icebreakers': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/icebreakers.post').default>>>>
    }
    '/api/auth/check-existing-user': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/check-existing-user.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/passkey/login-options': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/passkey/login-options.get').default>>>>
    }
    '/api/auth/passkey/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/passkey/login.post').default>>>>
    }
    '/api/auth/passkey/register-options': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/passkey/register-options.get').default>>>>
    }
    '/api/auth/passkey/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/passkey/register.post').default>>>>
    }
    '/api/auth/signup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/signup.post').default>>>>
    }
    '/api/auth/telegram': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/telegram.post').default>>>>
    }
    '/api/cron/auto-match': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/auto-match.get').default>>>>
    }
    '/api/cron/auto-verify': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/auto-verify.get').default>>>>
    }
    '/api/cron/engagement-nudge': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/engagement-nudge.get').default>>>>
    }
    '/api/cron/match-expiration-reminder': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/match-expiration-reminder.get').default>>>>
    }
    '/api/cron/match-feedback': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/match-feedback.get').default>>>>
    }
    '/api/cron/remind-profiles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/remind-profiles.get').default>>>>
    }
    '/api/cron/vibe-refresh': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/vibe-refresh.get').default>>>>
    }
    '/api/debug-column': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug-column.get').default>>>>
    }
    '/api/debug-data': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug-data.get').default>>>>
    }
    '/api/debug-event-column': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug-event-column.get').default>>>>
    }
    '/api/debug-join': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug-join.get').default>>>>
    }
    '/api/debug-schema': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug-schema.get').default>>>>
    }
    '/api/enrich_matches': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/enrich_matches.post').default>>>>
    }
    '/api/franchise/auth': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/franchise/auth.get').default>>>>
    }
    '/api/franchise/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/franchise/import.post').default>>>>
    }
    '/api/franchise/invite': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/franchise/invite.post').default>>>>
    }
    '/api/franchise/match': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/franchise/match.post').default>>>>
    }
    '/api/franchise/participant-data': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/franchise/participant-data.get').default>>>>
    }
    '/api/franchise/participant-delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/franchise/participant-delete.post').default>>>>
    }
    '/api/franchise/short-lookup': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/franchise/short-lookup.get').default>>>>
    }
    '/api/franchise/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/franchise/update.post').default>>>>
    }
    '/api/franchise/vote': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/franchise/vote.post').default>>>>
    }
    '/api/lobby/connect': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lobby/connect.post').default>>>>
    }
    '/api/lobby/debug-gender': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lobby/debug-gender.get').default>>>>
    }
    '/api/lobby/matches': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lobby/matches.get').default>>>>
    }
    '/api/lobby/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lobby/messages.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lobby/messages.post').default>>>>
    }
    '/api/lobby/participants': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lobby/participants.get').default>>>>
    }
    '/api/lobby/remind': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lobby/remind.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lobby/remind.post').default>>>>
    }
    '/api/matches': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/matches.get').default>>>>
    }
    '/api/me/notifications': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/me/notifications.get').default>>>>
    }
    '/api/otp/send': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/otp/send.post').default>>>>
    }
    '/api/otp/verify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/otp/verify.post').default>>>>
    }
    '/api/paystack/initialize': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/paystack/initialize.post').default>>>>
    }
    '/api/paystack/verify': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/paystack/verify.get').default>>>>
    }
    '/api/paystack/webhook-test': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/paystack/webhook-test.get').default>>>>
    }
    '/api/paystack/webhook': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/paystack/webhook.post').default>>>>
    }
    '/api/profiles/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profiles/create.post').default>>>>
    }
    '/api/profiles/trigger-match': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profiles/trigger-match.post').default>>>>
    }
    '/api/redemptions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/redemptions.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/redemptions.post').default>>>>
    }
    '/api/referrals': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/referrals/index.get').default>>>>
    }
    '/api/referrals/track': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/referrals/track.post').default>>>>
    }
    '/api/reports': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports.post').default>>>>
    }
    '/api/send-sms': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/send-sms.post').default>>>>
    }
    '/api/shots/:token': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shots/[token].get').default>>>>
    }
    '/api/shots': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shots/index.post').default>>>>
    }
    '/api/shots/unlock': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shots/unlock.post').default>>>>
    }
    '/api/sitemap.xml': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sitemap.xml.get').default>>>>
    }
    '/api/stats/social-proof': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats/social-proof.get').default>>>>
    }
    '/api/telegram/setup-webhook': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/telegram/setup-webhook.get').default>>>>
    }
    '/api/telegram/webhook': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/telegram/webhook.post').default>>>>
    }
    '/api/venues': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/venues.get').default>>>>
    }
    '/api/verify-admin-login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/verify-admin-login.post').default>>>>
    }
    '/api/vouches/:token': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vouches/[token].get').default>>>>
    }
    '/api/vouches': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vouches/index.post').default>>>>
    }
    '/api/vouches/respond': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vouches/respond.post').default>>>>
    }
    '/api/webhooks/zend-status': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/webhooks/zend-status.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/__nuxt_content/releaseNotes/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/info/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/releaseNotes/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/__nuxt_content/info/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
  }
}
export {}