// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/analytics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/analytics.get').default>>>>
    }
    '/api/admin/bulk-sms': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/bulk-sms.post').default>>>>
    }
    '/api/admin/notify-incomplete-profiles': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/notify-incomplete-profiles.post').default>>>>
    }
    '/api/admin/notify-missing-details': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/notify-missing-details.post').default>>>>
    }
    '/api/admin/request-match-feedback': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/request-match-feedback.post').default>>>>
    }
    '/api/admin/seed-users': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/seed-users.post').default>>>>
    }
    '/api/admin/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id].delete').default>>>>
    }
    '/api/auth/check-existing-user': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/check-existing-user.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/signup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/signup.post').default>>>>
    }
    '/api/cron/auto-match': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/auto-match.get').default>>>>
    }
    '/api/cron/match-expiration-reminder': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/match-expiration-reminder.get').default>>>>
    }
    '/api/enrich_matches': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/enrich_matches.post').default>>>>
    }
    '/api/matches': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/matches.get').default>>>>
    }
    '/api/me/notifications': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/me/notifications.get').default>>>>
    }
    '/api/paystack/initialize': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/paystack/initialize.post').default>>>>
    }
    '/api/paystack/verify': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/paystack/verify.get').default>>>>
    }
    '/api/paystack/webhook-test': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/paystack/webhook-test.get').default>>>>
    }
    '/api/paystack/webhook': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/paystack/webhook.post').default>>>>
    }
    '/api/profiles/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profiles/create.post').default>>>>
    }
    '/api/referrals': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/referrals/index.get').default>>>>
    }
    '/api/referrals/track': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/referrals/track.post').default>>>>
    }
    '/api/reports': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports.post').default>>>>
    }
    '/api/send-sms': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/send-sms.post').default>>>>
    }
    '/api/sitemap.xml': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sitemap.xml.get').default>>>>
    }
    '/api/verify-admin-login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/verify-admin-login.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}